version: '2'
services:
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
    cache:
        build:
            context: ./
            dockerfile: ./cache.docker